---

- name: install mysql 57 and dependencies
  apt: pkg={{ item }} install_recommends=yes force=yes state=present
  with_items:
    - software-properties-common
    - mysql-server-5.7

- name: start mysql
  service: name=mysql state=started

- name: install packages needed for single server
  apt: pkg={{','.join(edxlocal_debian_pkgs)}} install_recommends=yes state=present

- name: setup the edxapp db user
  mysql_user: >
    name={{ EDXAPP_MYSQL_USER }}
    password={{ EDXAPP_MYSQL_PASSWORD }}
    priv='{{ EDXAPP_MYSQL_DB_NAME }}.*:ALL'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: EDXAPP_MYSQL_USER is defined

- name: create a database for edxapp
  mysql_db: >
    db=edxapp
    state=present
    encoding=utf8
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: EDXAPP_MYSQL_USER is defined

- name: setup the xqueue db user
  mysql_user: >
    name={{ XQUEUE_MYSQL_USER }}
    password={{ XQUEUE_MYSQL_PASSWORD }}
    priv='{{ XQUEUE_MYSQL_DB_NAME }}.*:ALL'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: XQUEUE_MYSQL_USER is defined

- name: create a database for xqueue
  mysql_db: >
    db=xqueue
    state=present
    encoding=utf8
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: XQUEUE_MYSQL_USER is defined

- name: setup the ora db user
  mysql_user: >
    name={{ ORA_MYSQL_USER }}
    password={{ ORA_MYSQL_PASSWORD }}
    priv='{{ ORA_MYSQL_DB_NAME }}.*:ALL'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: ORA_MYSQL_USER is defined

- name: create a database for ora
  mysql_db: >
    db=ora
    state=present
    encoding=utf8
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: ORA_MYSQL_USER is defined

- name: create databases for analytics api
  mysql_db: >
    db={{ item }}
    state=present
    encoding=utf8
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: ANALYTICS_API_SERVICE_CONFIG is defined
  with_items:
    - "{{ ANALYTICS_API_SERVICE_CONFIG['DATABASES']['default']['NAME'] }}"
    - "{{ ANALYTICS_API_SERVICE_CONFIG['DATABASES']['reports']['NAME'] }}"

- name: create database for insights
  mysql_db: >
    db={{ INSIGHTS_DATABASES.default.NAME }}
    state=present
    encoding=utf8
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: INSIGHTS_DATABASES is defined

- name: create database for ecommerce
  mysql_db: >
    db="{{ ECOMMERCE_DEFAULT_DB_NAME }}"
    state=present
    encoding=utf8
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: ECOMMERCE_DEFAULT_DB_NAME is defined

- name: setup users for ecommerce
  mysql_user: >
    name="{{ ECOMMERCE_DEFAULT_DB_NAME }}"
    password="{{ ECOMMERCE_DATABASES.default.PASSWORD }}"
    priv='{{ ECOMMERCE_DEFAULT_DB_NAME }}.*:SELECT,INSERT,UPDATE,DELETE'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: ECOMMERCE_DEFAULT_DB_NAME is defined

- name: create api user for the analytics api
  mysql_user: >
    name=api001
    password="{{ ANALYTICS_API_DATABASES.default.PASSWORD }}"
    priv='{{ ANALYTICS_API_DATABASES.default.NAME }}.*:ALL/reports.*:SELECT'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: ANALYTICS_API_SERVICE_CONFIG is defined

- name: create read-only reports user for the analytics-api
  mysql_user: >
    name=reports001
    password="{{ ANALYTICS_API_DATABASES.reports.PASSWORD }}"
    priv='{{ ANALYTICS_API_DATABASES.reports.NAME }}.*:SELECT'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: ANALYTICS_API_SERVICE_CONFIG is defined

- name: setup the edx-notes-api db user
  mysql_user: >
    name={{ EDX_NOTES_API_MYSQL_DB_USER }}
    password={{ EDX_NOTES_API_MYSQL_DB_PASS }}
    priv='{{ EDX_NOTES_API_MYSQL_DB_NAME }}.*:SELECT,INSERT,UPDATE,DELETE'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: EDX_NOTES_API_MYSQL_DB_USER is defined

- name: create a database for edx-notes-api
  mysql_db: >
    db={{ EDX_NOTES_API_MYSQL_DB_NAME }}
    state=present
    encoding=utf8
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: EDX_NOTES_API_MYSQL_DB_USER is defined

- name: setup the migration db user
  mysql_user: >
    name={{ COMMON_MYSQL_MIGRATE_USER }}
    password={{ COMMON_MYSQL_MIGRATE_PASS }}
    priv='{{ item }}.*:ALL'
    append_privs=yes
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
  when: item != 'None'
  with_items:
    - "{{ EDXAPP_MYSQL_DB_NAME|default('None') }}"
    - "{{ XQUEUE_MYSQL_DB_NAME|default('None') }}"
    - "{{ ORA_MYSQL_DB_NAME|default('None') }}"
    - "{{ EDX_NOTES_API_MYSQL_DB_NAME|default('None') }}"
    - "{{ ANALYTICS_API_DEFAULT_DB_NAME|default('None') }}"
    - "{{ ANALYTICS_API_REPORTS_DB_NAME|default('None') }}"
    - "{{ INSIGHTS_DATABASE_NAME|default('None') }}"
    - "{{ ECOMMERCE_DEFAULT_DB_NAME|default('None') }}"

- name: setup the read-only db user
  mysql_user: >
    name={{ COMMON_MYSQL_READ_ONLY_USER }}
    password={{ COMMON_MYSQL_READ_ONLY_PASS }}
    priv='*.*:ALL'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
- name: setup the admin db user
  mysql_user: >
    name={{ COMMON_MYSQL_ADMIN_USER }}
    password={{ COMMON_MYSQL_ADMIN_PASS }}
    priv='*.*:CREATE USER'
    host='{{ EDXAPP_MYSQL_USER_HOST }}'
    login_user='{{ MYSQL_LOGIN_USER }}'
    login_password='{{ MYSQL_LOGIN_PASSWORD }}'
    login_host='{{ MYSQL_LOGIN_HOST }}'
    login_port='{{ MYSQL_LOGIN_PORT }}'
- name: copy MySQL configuration file
  template: >
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
  notify:
    - restart mysql
